name = "report-analyzer"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
output_dir = "client/dist"

[site]
bucket = "client/dist"

[build.environment]
NODE_VERSION = "18"

# 添加后端 API 配置
[[routes]]
pattern = "/api/*"
script = "server/api/index.py"

[env.production]
vars = { ENVIRONMENT = "production" } 