name = "report-analyzer"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
output_dir = "client/dist"

[site]
bucket = "client/dist"

[build.environment]
NODE_VERSION = "18"

# Workers 配置
[workers_dev]
enabled = true

[[workers]]
name = "report-api"
main = "server/api/index.py"
compatibility_date = "2024-01-01"

[[routes]]
pattern = "/api/*"
zone_name = "your-domain.com"
script = "report-api"

[env.production]
vars = { 
  ENVIRONMENT = "production",
  QIANFAN_AK = "your-ak",
  QIANFAN_SK = "your-sk"
} 