name = "report-analyzer"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
output_dir = "client/dist"

[site]
bucket = "client/dist"

[build.environment]
NODE_VERSION = "18"

[env.production]
vars = { ENVIRONMENT = "production" } 